#!/usr/bin/env php
<?php
date_default_timezone_set("PRC");

include_once __DIR__ . "/lib/HttpServer.php";
$configFile = __DIR__ . '/swoole_config.php';

array_shift($argv);
new HttpServer($argv, $configFile);
